services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5202:5202"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=RestaurantDb;User=sa;Password=P@ssw0rd!2025Secure;TrustServerCertificate=true
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd!2025Secure
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
